name: Run test

on:
  pull_request:
    branches: [main]

  jobs:
#    run on ubuntu latest
    build: ubuntu-latest
    steps:
#      1. Checkout first using third party https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

#      2. Setup JDK Using the version that I used third party https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK 21.05
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean test debug