name: Run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

#    run on ubuntu latest
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
#      1. Checkout first using third party https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4

#      2. Setup JDK Using the version that I used third party https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
